# Generated by Django 3.2.6 on 2021-10-02 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211002_2251'),
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_names',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='ds', max_length=700),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='ds', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default='ds', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='ds', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='OrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnty', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
